### ISSUE TITLE
Support more than 1 level deep of multipart data in incoming emails

### ISSUE THREAD

**Issue by charlescapps** [m242/maildrop#10]
I setup a Maildrop server for internal use at my company for QE email testing. 

However, for compatibility reasons with different servers, our email is sent in a format that looks like this:
multipart/mixed --> multipart/alternative --> text/plain, text/html

All of the emails from our product are being rejected with the error "no attachments", but it looks like the real reason for the error is that Maildrop doesn't find any of the "text/*" type fields.

See screenshot from wireshark of an example email:
![jive_email_wireshark](https://cloud.githubusercontent.com/assets/561671/7010114/d5cd51a4-dc53-11e4-8b72-9b8107dd7beb.png)

**Comment by charlescapps** [comment]
Actually, I added some debugging, and it looks like our email is failing to be parsed. 

When getContent() is called on the multipart message, it is returning a "SharedInputStream" instead of a "Multipart".

**Comment by m242** [comment]
Ugh-- this message is one of those rare types that makes parsing RFC1341 messages such a pain. The real solution here is to set up a recursive method that goes through a mime multipart and just grabs all text parts, and recursively calls itself for any multipart content items. Once you have the list of all text parts, you could probably just concatenate them together-- that would make the web display easier (we aren't trying to be Gmail after all).

**Comment by charlescapps** [comment]
Actually...it turns out that your code is going 2-levels deep, which is good enough. 

The problem mainly lies in Exceptions being squelched, so I couldn't figure out the root cause. I'm going to close out this ticket and create 2 new ones that are more descriptive.

**Comment by faust64** [comment]
Encountering with a similar issue, note the previous commit *might* fix.
Considering I have no idea what I just did, and little understanding what's going on, ... I can still confirm error message's gone ...
