### ISSUE TITLE
Alias inbox problems

### ISSUE THREAD

**Issue by stahlkarl** [m242/maildrop#15]
When an email is sent to an alias addr, it only shows up in the mailbox which generated the alias and not in the inbox for the alias.
Example:
alfred@maildrop.cc has alias D-2aa0sp7@maildrop.cc. Emails sent to D-2aa0sp7@maildrop.cc only shows up in http://maildrop.cc/inbox/alfred and not http://maildrop.cc/inbox/d-2aa0sp7 .

One might think this is due to the address alias collision issues (https://github.com/m242/maildrop/issues/14), but the problem persists even though the email address does not include any non-alfanumeric characters (that includes the alias address and the prefix).

**Comment by m242** [comment]
This is by design. When you give out the D-2aa0sp7 address, you don't want that someone to then go into /inbox/d-2aa0sp7 and read any subsequent messages.
