### ISSUE TITLE
sbt assembly errors

### ISSUE THREAD

**Issue by thinkpozzitive** [m242/maildrop#16]
Whenever I try to create the smtp jar via sbt assembly I get the following error. Do you have any idea how to fix this?

[info] Loading project definition from /home/test/Desktop/maildrop/smtp/project
[info] Loading project definition from /home/test/Desktop/maildrop/common/project
[info] Set current project to smtp (in build file:/home/test/Desktop/maildrop/smtp/)
[error] Not a valid command: assembly
[error] Not a valid project ID: assembly
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: assembly
[error] assembly
[error]         ^

Also with latest version of play framework, it's no longer "play dist" it is "activator dist". Maybe the installation instructions need an update?

**Comment by drampelt** [comment]
I managed to fix this by creating the file `smtp/project/assembly.sbt` with the contents:
```
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.13.0")
```

(Taken from the [sbt-assemby plugin page](https://github.com/sbt/sbt-assembly))

**Comment by thinkpozzitive** [comment]
works. Thanks.
