### ISSUE TITLE
Address alias collision - unusable alias

### ISSUE THREAD

**Issue by stahlkarl** [m242/maildrop#8]
Hi!
Than you for providing the source code for this excellent service!

While reading 
https://github.com/m242/maildrop/blob/master/common/src/main/scala/com/heluna/maildrop/util/AltInbox.scala
I realized that two identical addresses (except for the non alfa-numeric characters) would result in the same alias. Ex:
http://maildrop.cc/inbox/alfred
http://maildrop.cc/inbox/alfred+-~
Both have the alias: D-2aa0sp7@maildrop.cc

When sending an email to the alias address, it only appeared in the "alfred" inbox.

**Comment by m242** [comment]
They're also case insensitive; /inbox/alfred and /inbox/ALFRED will have the same alias. This is more or less by design, but if you want to strip this out, you can remove the ".toLowerCase.replaceAll" method calls in getAltInbox and getRegularInbox.
